// export const GET_FORECAST_REQUEST = 'GET_FORECAST_REQUEST';
export const GET_FORECAST_SUCCESS = "GET_FORECAST_SUCCESS";
export const GET_FORECAST_ERROR = "GET_FORECAST_ERROR";
export const FORECAST_SAGA = "FORECAST_SAGA";
export const GET_CITIES = "GET_CITIES";
